# pt_bins: [2, 3.5, 5, 8]
# ct_bins: [[1, 2, 4, 6, 8, 10, 14, 23],
#           [1, 2, 4, 6, 8, 10, 14, 23],
#           [1, 2, 4, 6, 8, 10, 14, 23]]
pt_bins: [2, 3, 4, 5.5, 8]
ct_bins: [[1, 3, 6, 9, 12, 18, 30],
          [1, 3, 6, 9, 12, 18, 25],
          [1, 3, 6, 9, 15, 25],
          [1, 3, 6, 10, 23]]
org_ctao: 7.6
mc_file: '../../results/absorption/absorption_tree_x1.5.root'
save_path: '../../results/absorption'
name_suffix: 'x1.5'